# Generated by Django 5.1.6 on 2025-03-25 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('photograph', models.CharField(blank=True, max_length=250, null=True, verbose_name='фотограф')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'дата',
                'verbose_name_plural': 'дата',
                'db_table': 'CategoryImages',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='merch_products_images', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='galery.categoriesimages', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
                'db_table': 'images',
                'ordering': ('id',),
            },
        ),
    ]
