# Generated by Django 5.1.6 on 2025-03-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriesimages',
            options={'ordering': ('-id',), 'verbose_name': 'дата', 'verbose_name_plural': 'дата'},
        ),
        migrations.AddField(
            model_name='categoriesimages',
            name='photograph',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='фотограф'),
        ),
    ]
