# Generated by Django 5.1.6 on 2025-04-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('date_realeese', models.DateField(verbose_name='Дата выхода')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='albums_images', verbose_name='Изображение')),
                ('listen_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на альбом')),
            ],
            options={
                'verbose_name': 'альбом',
                'verbose_name_plural': 'альбомы',
                'db_table': 'albums',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Singles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('author_text', models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор текста')),
                ('author_music', models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор музыки')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('listen_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на песню')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='songs_images', verbose_name='Изображение')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='song_videos', verbose_name='Видео')),
                ('date_realeese', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст песни')),
            ],
            options={
                'verbose_name': 'single',
                'verbose_name_plural': 'singles',
                'db_table': 'singles',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('author_text', models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор текста')),
                ('author_music', models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор музыки')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('listen_url', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на песню')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='songs_images', verbose_name='Изображение')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='song_videos', verbose_name='Видео')),
                ('date_realeese', models.DateField(blank=True, null=True, verbose_name='Дата выхода')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст песни')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='albums.albums', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'песню',
                'verbose_name_plural': 'песни',
                'db_table': 'songs',
                'ordering': ('id',),
            },
        ),
    ]
