# Generated by Django 5.1.6 on 2025-03-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='В обработке', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
