# Generated by Django 5.1.6 on 2025-03-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merch_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7, verbose_name='Цена'),
        ),
    ]
