# Generated by Django 5.1.6 on 2025-04-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('address', models.CharField(max_length=250, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'ссылку',
                'verbose_name_plural': 'ссылки',
                'db_table': 'addresses',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='ФИО')),
                ('profession', models.CharField(blank=True, max_length=250, null=True, verbose_name='Профессия')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('name_address_1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название соцсети')),
                ('address_1', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на соцсеть')),
                ('name_address_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название соцсети')),
                ('address_2', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на соцсеть')),
                ('name_address_3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название соцсети')),
                ('address_3', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ссылка на соцсеть')),
            ],
            options={
                'verbose_name': 'человека',
                'verbose_name_plural': 'люди',
                'db_table': 'persons',
                'ordering': ('id',),
            },
        ),
    ]
