# Generated by Django 5.1.5 on 2025-02-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_alter_categories_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ('id',), 'verbose_name': 'меню', 'verbose_name_plural': 'меню'},
        ),
    ]
