# Generated by Django 5.1.6 on 2025-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Заголовок')),
                ('date', models.DateTimeField()),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('place', models.CharField(max_length=250, verbose_name='Место проведения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='concerts_images', verbose_name='Изображение')),
                ('tickets', models.CharField(blank=True, max_length=150, null=True, verbose_name='Билеты')),
            ],
            options={
                'verbose_name': 'концерт',
                'verbose_name_plural': 'концерты',
                'db_table': 'concerts',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Заголовок')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='дата')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='info_images', verbose_name='Изображение')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='info_videos', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
                'db_table': 'info_about_group',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Заголовок')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images', verbose_name='Изображение')),
                ('videofile', models.FileField(blank=True, null=True, upload_to='news_videos', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'новости',
                'db_table': 'news',
                'ordering': ('-date',),
            },
        ),
    ]
