# Generated by Django 5.1.6 on 2025-03-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('-date',), 'verbose_name': 'событие', 'verbose_name_plural': 'события'},
        ),
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='info',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='info_videos', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='news',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='news_videos', verbose_name='Видео'),
        ),
    ]
