# Generated by Django 5.1.6 on 2025-03-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='info_images', verbose_name='Изображение'),
        ),
    ]
