# Generated by Django 5.1.6 on 2025-03-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
