# Generated by Django 5.1.6 on 2025-03-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата выхода')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'песня',
                'verbose_name_plural': 'песни',
                'db_table': 'songs',
                'ordering': ('-date',),
            },
        ),
    ]
