# Generated by Django 5.1.6 on 2025-03-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'ordering': ('-date_realeese',), 'verbose_name': 'песню', 'verbose_name_plural': 'песни'},
        ),
        migrations.AddField(
            model_name='songs',
            name='music',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор музыки'),
        ),
        migrations.AddField(
            model_name='songs',
            name='text',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Автор текста'),
        ),
    ]
